apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: podinfo
spec:
  host: podinfo.codygreen.local
  upstreams:
  - name: podinfo
    service: podinfo
    port: 80
  routes:
  - path: /
    action:
      pass: podinfo